# Apache Tomcat için server port ayarlamas?
server:
  port: 9090

# Hibernate için ve JDBC ba?lant?lar? için confgileri yaz?yoruz
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://5432/spring_jpa
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

